services:
  web:
    build: .
    container_name: hubmenu_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: hubmenu_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hubmenu
      MYSQL_USER: hubmenu_user
      MYSQL_PASSWORD: FOnoenp3o5623ionhono36
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "hubmenu_user", "-pFOnoenp3o5623ionhono36" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  db_data:
